##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-media
    - aptitude
    - autoconf-archive    
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmate-panel-applet-dev
    - libmatemixer-dev
    - libxml2-dev
    - make
    - mate-common

before_scripts:
  # Install mate-common fron tarball
  - ./html-cppcheck
  - ./install-from-git https://github.com/mate-desktop/mate-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-media/raw/master/data/icons/16x16/status/audio-input-microphone-high.png; fi
