##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-media
    - aptitude
    - autoconf-archive    
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - libglib2.0-dev
    - libxml2-dev
    - make

    #required for cafe-common
    - autoconf

    #required for libcafemixer
    - gettext
    - gtk-doc-tools
    - libasound2-dev
    - libpulse-dev
    - libtool

    #required for cafe-desktop
    - gobject-introspection
    - intltool
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-doc
    - libstartup-notification0-dev
    - libx11-dev

    #required for libvnck
    - gir1.2-freedesktop
    - libatk1.0-dev
    - libcairo2-dev
    - libice-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libsm-dev
    - libsoup-3.0-dev
    - libxau-dev
    - libxrandr-dev
    - lsb-release
    - meson
    - yelp-tools

    #required for libcafeweather
    - libxml2-utils
    - tzdata

    #required for libkanberra
    - gnome-pkg-tools
    - libltdl-dev
    - libvorbis-dev
    - libtdb-dev
    - libgstreamer1.0-dev

before_scripts:
  # Install cafe-common fron tarball
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 libctk-3-doc'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/libcafemixer master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/libvnck master meson
  - ./install-from-git https://github.com/cafe-desktop/cafe-menus master
  - ./install-from-git https://github.com/cafe-desktop/libcafeweather master
  - ./install-from-git https://github.com/cafe-desktop/cafe-panel master
  - ./install-from-git https://github.com/cafe-desktop/libkanberra master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-media/raw/master/data/icons/16x16/status/audio-input-microphone-high.png; fi
